title: Jack Ingledew-Gale
logo: /images/logo.jpg
description: >
  Data and GIS professional with 8+ years of industry experience
  in diverse positions in the UK and internationally.
  >
  Contact Details: j.ingledew@googlemail.com
#show_downloads: true
theme: jekyll-theme-minimal
