title: Jack Ingledew-Gale
#logo: /images/bg01.jpg
description: Data and GIS professional with 8+ years of industry experience in diverse 
positions in the UK and internationally.
#show_downloads: true
theme: jekyll-theme-minimal
