title: Jack Ingledew-Gale
logo: /images/logo.jpg
description: >
  I am a data and GIS professional with 8+ years of industry experience
  in diverse positions in the UK and internationally. My background is in
  climate change and I'm passionate about working in environmental science.
  Currently focussing on more development and automation-based earth observation projects.
#show_downloads: true
theme: jekyll-theme-minimal
