title: Jack Ingledew-Gale
logo: /images/logo.jpg
description: >
  Data and GIS professional with 8+ years of industry experience
  in diverse positions in the UK and internationally.

  Contact Details: j.ingledew@googlemail.com
summary: >
  Expert in spatial data analysis, mapping, and GIS software.
  Skilled in data visualization and geospatial data management.

# Optionally, you can add more descriptive fields with unique names as needed.
background: >
  Holds a Master's degree in Geographic Information Systems (GIS)
  from the University of Somewhere. Certified in advanced data analysis techniques.

#show_downloads: true
theme: jekyll-theme-minimal
